### ISSUE TITLE
Feature Request: Export to CSV Functionality

### ISSUE THREAD

**Issue by NxtTAB** [greenhats-gmbh/flc#2]
Hello,

I am currently using [Product/Software Name] for document creation and have found that a direct export to CSV functionality is missing. This feature would greatly simplify the process of generating documents, especially when dealing with large datasets that need to be analyzed or shared in a spreadsheet format.

Proposed Solution:

It would be extremely beneficial if an 'Export to CSV' option could be implemented, allowing users to directly export their data into a CSV file. This would streamline workflows and enhance productivity by reducing the steps currently needed to convert data into a usable format.

Benefits:

Efficiency: Reduces the time and effort required to convert and format data manually.
Usability: Makes the software more accessible to users who frequently work with spreadsheets.
Compatibility: Ensures that data exported from [Product/Software Name] can be easily used in other applications that support CSV formats.
Thank you for considering this enhancement. I believe it would significantly improve the user experience for many of your clients.

**Comment by FLX-0x00** [comment]
PR welcome
